apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zml8yrmvj-go 
  janus-idp.io/tekton: zml8yrmvj-go
  backstage.io/kubernetes-id: zml8yrmvj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zml8yrmvj-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  