apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: zml8yrmvj-go-gitops
  description: This is GitOps manifest for zml8yrmvj-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=zml8yrmvj-go
    backstage.io/kubernetes-id: zml8yrmvj-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: zml8yrmvj-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:zml8yrmvj-go
